version: 1.4.0

branches:
  only:
  - master
skip_non_tags: true
  
image: Visual Studio 2022
  
init:
  - git config --global core.autocrlf true
  
before_build:
 - cmd: nuget restore    
 - cmd: dotnet restore APIWizard.sln

build_script:
 - cmd: dotnet build APIWizard /p:AssemblyVersion=%appveyor_build_version% /p:InformationalVersion=%appveyor_build_version%
 - cmd: dotnet test APIWizard.Tests /p:AssemblyVersion=%appveyor_build_version% /p:InformationalVersion=%appveyor_build_version%
 - cmd: dotnet pack APIWizard /p:AssemblyVersion=%appveyor_build_version% /p:InformationalVersion=%appveyor_build_version% /p:PackageVersion=%appveyor_build_version% 
 
artifacts:
 - path: '**\*.nupkg' 
   type: 'NuGetPackage'
   name: 'api-wizard'

deploy:
- provider: Environment
  name: api-wizard-nuget
  artifact: 'APIWizard.1.1.0.nupkg'
